# Generated by Django 3.0.5 on 2021-03-14 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dzialki_aspect_wgs_dobre',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('objectid', models.CharField(max_length=254)),
                ('identyfika', models.CharField(max_length=254)),
                ('powierzchn', models.CharField(max_length=254)),
                ('teryt', models.CharField(max_length=254)),
                ('numer', models.CharField(max_length=254)),
                ('obreb', models.CharField(max_length=254)),
                ('wojewodztw', models.CharField(max_length=254)),
                ('powiat', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('data_od', models.CharField(max_length=254)),
                ('shape_leng', models.CharField(max_length=254)),
                ('shape_area', models.CharField(max_length=254)),
                ('obwod', models.FloatField()),
                ('pole_ar', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='dzialki_razem_wgs_dobre',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('objectid', models.CharField(max_length=254)),
                ('identyfika', models.CharField(max_length=254)),
                ('numer', models.CharField(max_length=254)),
                ('obreb', models.CharField(max_length=254)),
                ('wojewodztw', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('shape_area', models.CharField(max_length=254)),
                ('pole_ar', models.FloatField()),
                ('powierzchn', models.CharField(max_length=254)),
                ('teryt', models.CharField(max_length=254)),
                ('powiat', models.CharField(max_length=254)),
                ('shape_leng', models.CharField(max_length=254)),
                ('obwod', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='dzialki_slope_wgs',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('objectid', models.CharField(max_length=254)),
                ('identyfika', models.CharField(max_length=254)),
                ('numer', models.CharField(max_length=254)),
                ('obreb', models.CharField(max_length=254)),
                ('wojewodztw', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('shape_area', models.CharField(max_length=254)),
                ('pole_ar', models.FloatField()),
                ('obwod', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='dzialki_wszystkie_wgs',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('objectid', models.CharField(max_length=254)),
                ('identyfika', models.CharField(max_length=254)),
                ('powierzchn', models.CharField(max_length=254)),
                ('teryt', models.CharField(max_length=254)),
                ('numer', models.CharField(max_length=254)),
                ('obreb', models.CharField(max_length=254)),
                ('wojewodztw', models.CharField(max_length=254)),
                ('powiat', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('data_od', models.CharField(max_length=254)),
                ('shape_leng', models.CharField(max_length=254)),
                ('shape_area', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='dzialki_wszystkie_wgs_dobre',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('objectid', models.CharField(max_length=254)),
                ('identyfika', models.CharField(max_length=254)),
                ('powierzchn', models.CharField(max_length=254)),
                ('teryt', models.CharField(max_length=254)),
                ('numer', models.CharField(max_length=254)),
                ('obreb', models.CharField(max_length=254)),
                ('wojewodztw', models.CharField(max_length=254)),
                ('powiat', models.CharField(max_length=254)),
                ('gmina', models.CharField(max_length=254)),
                ('shape_leng', models.CharField(max_length=254)),
                ('shape_area', models.CharField(max_length=254)),
                ('pole_ar', models.FloatField()),
                ('obwod', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=2)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('un', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.BigIntegerField()),
                ('region', models.IntegerField()),
                ('subregion', models.IntegerField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, spatial_index=False, srid=4326)),
            ],
        ),
    ]
